# Generated by Django 4.1.7 on 2023-03-09 04:42

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Aya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('user', models.OneToOneField(default=User.models.User, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='BookMark', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('aya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookMarks', to='Aya.aya', verbose_name='Aya')),
            ],
            options={
                'verbose_name': 'BookMark',
                'verbose_name_plural': 'BookMarks',
            },
        ),
    ]
